export const CHANGE_PRINCIPAL = "CHANGE_PRINCIPAL";
export const UPDATE_LOAN_TERMS = "UPDATE_LOAN_TERMS";
export const UPDATE_PAYMENTS = "UPDATE_PAYMENTS";
export const OPEN_PAYMENTS = "OPEN_PAYMENTS";
export const CLOSE_PAYMENTS = "CLOSE_PAYMENTS";